# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-27 11:16
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20161202_1759'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
    ]
